apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bookstore
  labels:
    app.kubernetes.io/component: bookstore
    app.kubernetes.io/instance: bookstore
    app.kubernetes.io/name: bookstore
    app.kubernetes.io/part-of: bookstore
    app.openshift.io/runtime: bookstore
    app.openshift.io/runtime-version: latest
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "15s"
        autoscaling.knative.dev/maxScale: "10"
      labels:
        app.kubernetes.io/component: bookstore
        app.kubernetes.io/instance: bookstore
        app.kubernetes.io/name: bookstore
        app.kubernetes.io/part-of: bookstore
        app.openshift.io/runtime: bookstore
        app.openshift.io/runtime-version: latest
    spec:
      containerConcurrency: 1
      containers:
        - image: quay.io/jpacker/hugo-nginx:latest
          imagePullPolicy: Always
          name: hugo-nginx
          ports:
            - containerPort: 8080
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
